services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-nginx-docker
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
networks:
  default: